import { Geist, Geist_Mono, Carlito } from "next/font/google";
import "./globals.css";
import "../lib/registerChart.js";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const carlito = Carlito({
  variable: "--font-carlito",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${carlito.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
